name: Deploy RunPT-AI to EC2


on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_KEY: ${{ secrets.EC2_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem

      - name: Upload project to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} "mkdir -p ~/RunPT-AI"
          scp -o StrictHostKeyChecking=no -i key.pem -r ./* ${EC2_USER}@${EC2_HOST}:~/RunPT-AI/

      - name: Install dependencies in venv
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} "
            cd ~/RunPT-AI;

            # venv 없으면 생성
            if [ ! -d 'venv' ]; then
              echo 'Creating venv...';
              python3 -m venv venv;
            fi

            # venv 안에서 패키지 설치
            ./venv/bin/pip install --upgrade pip;
            ./venv/bin/pip install -r requirements.txt;
          "

      - name: Restart FastAPI service
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} "
            sudo systemctl daemon-reload;
            sudo systemctl restart runpt || true;
          "
